# Builtin native plugins: QIANJS_MODULE_* options, plugin spec list, glue header generation.
# Included from project root CMakeLists.txt before add_subdirectory(src/native).

function(qianjs_native_register_module SUBDIR PLUGIN_CLASS HEADER_UNDER_SRC)
    string(TOUPPER "${SUBDIR}" _up)
    set(_opt "QIANJS_MODULE_${_up}")
    option(${_opt} "QianJS native module (${SUBDIR})" ON)
    set_property(GLOBAL APPEND PROPERTY QIANJS_PLUGIN_SPECS "${_up}|${PLUGIN_CLASS}|${HEADER_UNDER_SRC}")
endfunction()

function(qianjs_write_native_glue out_dir)
    get_property(_specs GLOBAL PROPERTY QIANJS_PLUGIN_SPECS)
    if(NOT _specs)
        set(_specs "")
    endif()

    set(_defs "#pragma once\n/* Generated by CMake — do not edit. */\n\n")
    set(_glue "#pragma once\n/* Generated by CMake — do not edit. */\n#include <qianjs_modules.h>\n#include <js_plugin.h>\n\n")
    set(_fn "\ninline void qianjs_populate_default_plugins(qjs::PluginRegistry& r) {\n")

    foreach(spec ${_specs})
        string(REPLACE "|" ";" _p ${spec})
        list(LENGTH _p _len)
        if(NOT _len EQUAL 3)
            message(FATAL_ERROR "Invalid QIANJS_PLUGIN_SPECS entry (expected MACRO|Class|header): ${spec}")
        endif()
        list(GET _p 0 _macro)
        list(GET _p 1 _class)
        list(GET _p 2 _hdr)

        if(QIANJS_MODULE_${_macro})
            string(APPEND _defs "#define QIANJS_MODULE_${_macro} 1\n")
        else()
            string(APPEND _defs "#define QIANJS_MODULE_${_macro} 0\n")
        endif()

        string(APPEND _glue "#if QIANJS_MODULE_${_macro}\n#include \"${_hdr}\"\n#endif\n")
        string(APPEND _fn "#if QIANJS_MODULE_${_macro}\n  r.emplace<${_class}>();\n#endif\n")
    endforeach()

    string(APPEND _fn "}\n")

    file(WRITE "${out_dir}/qianjs_modules.h" "${_defs}")
    file(WRITE "${out_dir}/qianjs_default_plugins.g.h" "${_glue}${_fn}")
endfunction()

set_property(GLOBAL PROPERTY QIANJS_PLUGIN_SPECS "")

qianjs_native_register_module(console ConsolePlugin native/console/console_module.h)
qianjs_native_register_module(fs FsPlugin native/fs/fs_module.h)
qianjs_native_register_module(net NetPlugin native/net/net_module.h)
qianjs_native_register_module(process ProcessPlugin native/process/process_module.h)
qianjs_native_register_module(timers TimersPlugin native/timers/timers_module.h)
