# Sokol 图形库配置
# sokol 是单头文件库，需要在一个编译单元中实现

set(SOKOL_DIR ${CMAKE_SOURCE_DIR}/third_party/sokol)
set(SOKOL_BUILD_DIR ${CMAKE_BINARY_DIR}/sokol)

# 检查 sokol 子模块是否存在
if(NOT EXISTS ${SOKOL_DIR}/sokol_app.h)
    message(FATAL_ERROR "Sokol not found. Please run: git submodule update --init --recursive")
endif()

# 创建 sokol 构建目录
file(MAKE_DIRECTORY ${SOKOL_BUILD_DIR})

# 创建 sokol 实现文件
# 在 macOS 上使用 Objective-C (.m) 以支持 Metal
# 在其他平台使用 C (.c)
if(APPLE)
    set(SOKOL_IMPL_FILE ${SOKOL_BUILD_DIR}/sokol_impl.m)
else()
    set(SOKOL_IMPL_FILE ${SOKOL_BUILD_DIR}/sokol_impl.c)
endif()

file(WRITE ${SOKOL_IMPL_FILE}
"// Sokol implementation file
// Auto-generated by cmake/sokol.cmake

#define SOKOL_IMPL
#define SOKOL_NO_ENTRY

// 平台检测
#if defined(_WIN32)
    #define SOKOL_D3D11
#elif defined(__APPLE__)
    #define SOKOL_METAL
#else
    #define SOKOL_GLCORE33
#endif

// 包含 sokol 头文件
#include \"sokol_app.h\"
#include \"sokol_gfx.h\"
#include \"sokol_log.h\"
#include \"sokol_glue.h\"
")

# 添加 sokol 库
add_library(sokol STATIC ${SOKOL_IMPL_FILE})

target_include_directories(sokol PUBLIC ${SOKOL_DIR})

# 平台特定链接
if(APPLE)
    target_link_libraries(sokol PUBLIC
        "-framework Cocoa"
        "-framework QuartzCore"
        "-framework Metal"
        "-framework MetalKit"
    )
elseif(UNIX)
    find_package(X11 REQUIRED)
    target_link_libraries(sokol PUBLIC
        X11::X11
        X11::Xi
        X11::Xcursor
        GL
        dl
        pthread
    )
elseif(WIN32)
    target_link_libraries(sokol PUBLIC
        d3d11
        dxgi
        dxguid
    )
endif()
